# Generated by Django 2.2.1 on 2019-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=42, unique=True)),
                ('first_block', models.IntegerField(null=True)),
            ],
        ),
    ]
